name: Rust

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
      fail-fast: false

    steps:
      - uses: actions/checkout@v1

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
          echo ::add-path::$HOME/.cargo/bin

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
