name: Rust

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
      fail-fast: false

    steps:
      - uses: actions/checkout@v1

      - name: Install Rust
        if: contains(matrix.os, 'macOS')
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          rustup toolchain install stable
          cargo build --verbose
          cargo test --verbose

      - name: Build
        if: not(contains(matrix.os, 'macOS'))
        run: cargo build --verbose

      - name: Run tests
        if: not(contains(matrix.os, 'macOS'))
        run: cargo test --verbose
