name: Rust

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
      fail-fast: false

    steps:
      - uses: actions/checkout@v1

      - name: Install Rust
        if: contains(matrix.os, 'macOS')
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh && rustup toolchain install stable

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
